arch: resnet50
batch_size: 32
dataset: cifar10
exclude_bn_bias: false
feat_dim: 128
final_lr: 0.0
first_conv: true
gpus: 1
hidden_mlp: 2048
learning_rate: 0.001
max_epochs: 100
maxpool1: true
num_nodes: 1
num_samples: 40000
optimizer: adam
start_lr: 0.0
temperature: 0.1
warmup_epochs: 10
weight_decay: 1.0e-06
